### ISSUE TITLE
Raid Toolkit does not run with new PlariumPlay

### ISSUE THREAD

**Issue by Sachmet-Netjer** [raid-toolkit/raid-toolkit-sdk#82] opened 2022-08-03 20:44 UTC
Hi there,
RaidToolkit looks for gamestorage.gsfn, which was located in 'C:\Users\...\AppData\Local\Plarium\PlariumPlay\gamestorage.gsfn'. The new installation of PlariumPlay v8 stores that file in 'C:\Users\...\AppData\Local\PlariumPlay\gamestorage.gsfn' instead. this results in a "System.IO.DirectoryNotFoundException: Could not find a part of the path ".
The installation from scratch of both, RaidToolkit and PlariumPlay, did not help.

Best Regards
Sachmet-Netjer

**Comment by Sachmet-Netjer** [comment] 2022-08-04 12:20
With the actual version RaidToolkit, v1.10.2.4452, the problem seems to be solved.
In this context I have an additional question, that bothers me for quite some time.
After installing the version above the tooltip tells me I run v1.10.2.25617. Where does that mismatch come from? In former versions aswell it happened that for several releases the tooltip did not change.

Best Regards
Sachmet-Netjer

**Comment by dnchattan** [comment] 2022-08-04 13:34
> After installing the version above the tooltip tells me I run v1.10.2.25617. Where does that mismatch come from? In former versions aswell it happened that for several releases the tooltip did not change.

I only recently figured this one out, it's been driving me nuts.  The mismatch is caused by a change in the `Nerdbank.GitVersioning` dependency that was causing a different version number to be emitted for the release name than was being stamped into the assembly. This is fixed in 2.0, but I haven't ported back to 1.10.x yet.

**Comment by dnchattan** [comment] 2022-08-04 14:39
Latest 1.10.3.6975 release should have matching version numbers

**Closed by dnchattan** 2022-08-04 14:39 UTC
