### ISSUE TITLE
Feature request: 'getArena' command for Raid Toolkit Python Lib.

### ISSUE THREAD

**Issue by WOROTH** [raid-toolkit/raid-toolkit-sdk#40] opened 2021-11-18 02:20 UTC

**Comment by dnchattan** [comment] 2021-11-19 22:53
which specific data are you expecting it to return?

**Comment by dnchattan** [comment] 2021-11-19 22:55
is this a dupe of #28?

**Comment by WOROTH** [comment] 2021-11-20 11:34
The same content as inside '.\data\acc\arena'

**Comment by dnchattan** [comment] 2021-11-22 23:29
now available :)

**Closed by dnchattan** 2021-11-22 23:29 UTC
Labels: question

**Comment by WOROTH** [comment] 2021-11-22 23:31
Great! Thanks! :)
